spring:
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://localhost:3306/lit?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  freemarker:
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: rc
    prefer-file-system-access: false
  jackson:
    default-property-inclusion: non_empty


lit:
  configure:
    single-page: true



logging:
  level:
    com.github: debug
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.access.prepost: info

#        security: debug

---
spring:
  profiles: docker
c3p0:
  jdbcUrl: jdbc:mysql://${mysql-docker:mysql-server}:3306/lit
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: 123456

