c3p0:
  jdbcUrl: jdbc:mysql://localhost:3306/lit
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: 123456
#  jdbcUrl: jdbc:oracle:thin:@localhost:49161:XE
#  driverClass: oracle.jdbc.OracleDriver
#  user: liulu
#  password: 123456


spring:
  profiles:
    active: default
  thymeleaf:
    cache: false
  freemarker:
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: rc
    prefer-file-system-access: false


server:
  context-path: /lit


---

spring:
  profiles: dev
c3p0:
  jdbcUrl: jdbc:mysql://120.78.47.145:3306/lit
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: Lycd1993981!