c3p0:
  jdbcUrl: jdbc:mysql://localhost:3306/lit
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: 123456


spring:
  profiles:
    active: default
  freemarker:
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: rc
    prefer-file-system-access: false
  jackson:
    default-property-inclusion: non_empty
lit:
  render:
    header: false
    left: false


server:
  context-path: /lit


---
spring:
  profiles: docker
c3p0:
  jdbcUrl: jdbc:mysql://${mysql-docker:mysql-server}:3306/lit
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: 123456

